// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWeb_LeVanThanhDat.Models;

namespace TestWeb_LeVanThanhDat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWeb_LeVanThanhDat.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 700m,
                            Quantity = 1,
                            Title = "TÂM"
                        },
                        new
                        {
                            Id = 2,
                            Price = 800m,
                            Quantity = 1,
                            Title = "ASP.NET"
                        },
                        new
                        {
                            Id = 3,
                            Price = 750m,
                            Quantity = 1,
                            Title = "PHP"
                        },
                        new
                        {
                            Id = 4,
                            Price = 600m,
                            Quantity = 1,
                            Title = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Price = 900m,
                            Quantity = 1,
                            Title = "Trình là gì ?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
